quarkus.openfeature.provider=runtime-config,buildtime-config
quarkus.openfeature.runtime.runtime-flag=from-runtime
quarkus.openfeature.buildtime.buildtime-flag=from-buildtime
quarkus.openfeature.runtime.overridden=runtime-wins
quarkus.openfeature.buildtime.overridden=buildtime-value

quarkus.openfeature."custom".provider=runtime-config
quarkus.openfeature."custom".runtime.custom-flag=custom-value
